# Generated by Django 2.1.5 on 2019-06-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('first', models.FloatField()),
                ('second', models.FloatField()),
                ('sign', models.CharField(max_length=15)),
                ('user_answer', models.FloatField()),
            ],
        ),
    ]
