# Generated by Django 2.1.5 on 2019-06-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_math', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('answers_options', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Task02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('contest01_task_id', models.IntegerField()),
                ('user_answer', models.CharField(max_length=255)),
            ],
        ),
    ]
