# Generated by Django 2.1.5 on 2019-09-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishIrregularVerbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infinitive', models.CharField(max_length=50)),
                ('past', models.CharField(max_length=50)),
                ('participle', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50)),
            ],
        ),
    ]
